spring.application.name=Employee_CURD_Swagger_Project

spring.datasource.url=jdbc:mysql://localhost:3306/employee_db
spring.datasource.username=root
spring.datasource.password=mahant@1931

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# custom JWT property used by application code
jwt.secret=mysecretkey_mysecretkey_mysecretkey

server.port=${PORT:8080}
