spring.application.name=Employee_CURD_Swagger_Project

ring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# custom JWT property used by application code
jwt.secret=mysecretkey_mysecretkey_mysecretkey

server.port=${PORT:8080}
